# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f98fec16eb4a233512f04ae58d256c4a99a51f871c8dd106d74d3fc46b4300361eb0b8a9d1bc979c6209327c7be6837b173b8cd34086edfb00256d6b67e957e

test:
  secret_key_base: 6e7c6fdc0ce90c3cc84c0d64d0239acd175980b8227ae802aabd484313e0fd5e766c29cc7b3c8a148d5b511ffdbf3f71be99119e82149af91e9ef1f801e44134

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
